// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixjxlfawgkbcbljhlfid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4anhsZmF3Z2tiY2JsamhsZmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODExNjQsImV4cCI6MjA1NzU1NzE2NH0.y4yX3DXQ9HBZOeJivG5QObJvuSJ7S2UGtTvVsRwZGwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);